### ISSUE TITLE
Can't run demo "Jaccard Similarity between Dependency Trees"

### ISSUE THREAD

**Issue by knit-bee** [ulf1/treesimi#51]
The cell where the minhashes are created throws an ValueError

![Bildschirmfoto von 2021-11-12 09-55-34](https://user-images.githubusercontent.com/75680321/141439454-1cbedfa4-3ed2-4d03-a6f1-c0d71449b997.png)

**Comment by knit-bee** [comment]
The error seems to occur for sentences with contractions of article and preposition (e.g. 'im', 'zur'). The conll-data has extra rows for the contracted form and the underlying isolated forms, thus the index of a token becomes for example (13, '-', 14) (see traceback).

Maybe you can just skip the row with the contracted form?

**Comment by ulf1** [comment]
I see

```
...
((13, '-', 14), None, '_', 'im'),
 (13, 16, 'case', 'in'),
 (14, 16, 'det', 'dem'),
...
```

`(13, '-', 14)` is actually `13-14`
and additional information that we don't need at this stage.

https://universaldependencies.org/format.html#words-tokens-and-empty-nodes
