### ISSUE TITLE
can't use spacy with treesimi

### ISSUE THREAD

**Issue by knit-bee** [ulf1/treesimi#53]
When using the spacy dependency parser and trying to turn the adjacency list into a nested set representation, a ValueError is thrown when searching for node indices.

![Bildschirmfoto von 2021-11-22 11-26-02](https://user-images.githubusercontent.com/75680321/142845201-e9e6c1e9-e623-4399-a6df-2ca9d42ea39e.png)
.

**Comment by ulf1** [comment]
### Cause
- multiple dependency trees cannot be processed by `adjac_to_nested` (Only the 1st adjacency list is transformed to a nested set list; All other trees are ignored)

### TODO
- [ ] ~~util fn to split adjacency lists with multiple trees in single trees~~
- [ ] Provide another demo notebook
